### ISSUE TITLE
WebSocket connection with self signed certificate

### ISSUE THREAD

**Issue by giosava94** [wduckitt/React-Automation-Studio#12]
Hello,

when I try to use React-Automation-Studio-Example-Project-1 with https in production mode I can load the page correctly but the websocket connection to the pvServer fails.

I am using self-signed certificates.

## ENVIRONMENT

- Using React-Automation-Studio-Example-Project V2.0.0 on Ubuntu 18.04 LTS

## PROCEDURE

Here what I did:

- I create the certificates on the host pc with the following commands (starting from the repository main folder):

~~~
cd certificates 

openssl genrsa -des3 -out test-ca.key 2048
openssl req -x509 -new -nodes -key test-ca.key -sha256 -days 3650 -out test-ca.pem

openssl genrsa -out server.key 2048
openssl req -new -key server.key -out server.csr
openssl x509 -req -in server.csr -CA test-ca.pem -CAkey test-ca.key -CAcreateserial -out server.cer -days 3650 -sha256
~~~

- I set the environment variables to:

.env file
~~~
REACT_APP_FrontendServerPORT=443
REACT_APP_PyEpicsServerBASEURL=https://<HOST_NAME>
~~~

> The HOST_NAME is the same given to the *Common Name* property asked when creating the certificates

- Successfully build the project:

~~~
docker-compose build
~~~

- Start the containers

~~~
docker-compose up
~~~

## OUTPUT

All containers correctly starts and reading the output messages I confirm that the pvServer URL is correct (both URL and port number).

When I open, from the same pc running the dockers, a tab with the correct link on firefox, the pvServer sends the following error:

~~~
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.8/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python3.8/site-packages/gevent/server.py", line 201, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
  File "/usr/local/lib/python3.8/site-packages/gevent/_ssl3.py", line 688, in wrap_socket
    return SSLSocket(sock=sock, keyfile=keyfile, certfile=certfile,
  File "/usr/local/lib/python3.8/site-packages/gevent/_ssl3.py", line 267, in __init__
    raise x
  File "/usr/local/lib/python3.8/site-packages/gevent/_ssl3.py", line 263, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.8/site-packages/gevent/_ssl3.py", line 587, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1124)
2020-09-30T08:58:25Z <Greenlet at 0x7f1e7ce7e8c0: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed]  object, fd=-1, )> failed with SSLError
~~~

In this case I can move through the frontend pages but the connection with the PVs does not work. 

The firefox console shows the following error:

~~~
Firefox can’t establish a connection to the server at wss://<HOST_NAME>:5000/socket.io/?EIO=3&transport=websocket.
~~~

## VARIANTS

I tried also to set the environment variable **REACT_APP_EnableLogin** to **true**. This way the authentication can't be executed and I am stuck in the Login page.
I tried to look on internet for similar problems but it is not clear if it is a problem on the server side or on the client side.

**Comment by wduckitt** [comment]
I think it might be your self signed certificate.

ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1124)

We use CA signed one, and have no problems.

**Comment by wduckitt** [comment]
Hi Giovanni

Like I mentioned earlier at the lab we use CA signed certificates.

I used your method of signing but I get the same error.

I followed this post:
https://blog.miguelgrinberg.com/post/running-your-flask-application-over-https

On my ubuntu 18.04 system at home -yes we are still in lockdown :( , in
certificates folder I used:

openssl req -x509 -newkey rsa:4096 -nodes -out server.cer -keyout
server.key -days 365

My .env looks like:

#.env file


REACT_APP_PyEpicsServerBASEURL=https://MY_IP
REACT_APP_EnableLogin=true
REACT_APP_FrontendServerPORT=443
REACT_APP_PyEpicsServerPORT=5000



after rebuilding:

docker-compose -f docker-compose-prod-with-demoioc.yml up --build


Everything connects.

I still get an exception the unknown CA, although it doesnt crash the
server. Perhaps we can figure out how to catch it.

 Traceback (most recent call last):
stagingprodpvserver_1               |   File "src/gevent/greenlet.py", line
766, in gevent._greenlet.Greenlet.run
stagingprodpvserver_1               |   File
"/usr/local/lib/python3.7/site-packages/gevent/baseserver.py", line 26, in
_handle_and_close_when_done
stagingprodpvserver_1               |     return handle(*args_tuple)
stagingprodpvserver_1               |   File
"/usr/local/lib/python3.7/site-packages/gevent/server.py", line 201, in
wrap_socket_and_handle
stagingprodpvserver_1               |     with
_closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as
ssl_socket:
stagingprodpvserver_1               |   File
"/usr/local/lib/python3.7/site-packages/gevent/_ssl3.py", line 693, in
wrap_socket
stagingprodpvserver_1               |     ciphers=ciphers)
stagingprodpvserver_1               |   File
"/usr/local/lib/python3.7/site-packages/gevent/_ssl3.py", line 267, in
__init__
stagingprodpvserver_1               |     raise x
stagingprodpvserver_1               |   File
"/usr/local/lib/python3.7/site-packages/gevent/_ssl3.py", line 263, in
__init__
stagingprodpvserver_1               |     self.do_handshake()
stagingprodpvserver_1               |   File
"/usr/local/lib/python3.7/site-packages/gevent/_ssl3.py", line 587, in
do_handshake
stagingprodpvserver_1               |     self._sslobj.do_handshake()
stagingprodpvserver_1               | ssl.SSLError: [SSL:
SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown
(_ssl.c:1076)
stagingprodpvserver_1               | 2020-09-30T13:55:27Z <Greenlet at
0x7f0500c2acb0: _handle_and_close_when_done(<bound method
StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close
of <WSGIServer, (<gevent._socket3.socket [closed]  object, fd=-1, )> failed
with SSLError

**Comment by giosava94** [comment]
Hi,
we looked into this problem all the day and we found that, with your same .env file, going to the link `https://<HOST_IP>` the page shows a warning asking us if we want to accept the certificate or not. We accept it (as before) and we can see the frontend page but the frontend can't communicate with the backend.

In fact, accepting that certificate is not enough. Going to `https://<HOST_IP>:<PV_SERVER_PORT>` (in your case 5000) the browser ask you again to accept a certificate, which is the same accepted before. Accepting also this exception the communication correctly works!

I add a link to a discussion explaining this same procedure.
https://bugzilla.mozilla.org/show_bug.cgi?id=700837

It seams that this happens only on firefox.

Thanks for your attention

**Comment by wduckitt** [comment]
Oh ok, I only use chrome. It's also annoying you can't use self
signed certificates in PWA mode as it displays a massive bar over the top
of the app that the site is unsecure.
It forces you to own a domain and then have CA signed certificate.

Im going to close this issue
