### ISSUE TITLE
mongosetup in docker-compose treats failure as success

### ISSUE THREAD

**Issue by hanak** [wduckitt/React-Automation-Studio#25]
**Problem**
When an exception occurs in `replSetup.py` and it is not expected, it prints it out on stdout. Then, the script terminates with an exit code 0 even though it did not really complete.

**Example**
I have encountered an exception with a message "command replSetGetStatus requires authentication". Following this, `initializeadmindb` kept failing. Yet, an issue was encountered in earlier step.

**Comment by wduckitt** [comment]
Thanks, Justin will look into it

**Comment by justinabraham** [comment]
Hi,

The default docker-compose starts up the mongodb databases with no user/pass so not sure why it requires authentication.

Nonetheless, errors during replica set instantiation will now be raised and exit with non zero code.

Will merge in V3.0.1
