### ISSUE TITLE
docker-compose intializeadmindb continues even though it misses ADMIN_DATABASE_REPLICA_SET_NAME

### ISSUE THREAD

**Issue by hanak** [wduckitt/React-Automation-Studio#26]
**Problem**
If ADMIN_DATABASE_REPLICA_SET_NAME is not defined, the module `adminDbInit/initDb.py` continues assuming ADMIN_DATABASE_REPLICA_SET_NAME is set to a string "None". This fails later.

**Proposed Solution**
I think there are two options:
1) Use `ADMIN_DATABASE_REPLICA_SET_NAME=os.environ['ADMIN_DATABASE_REPLICA_SET_NAME']`. This will crash if `ADMIN_DATABASE_REPLICA_SET_NAME` is not defined. While this is not ideal, it crashes at the place of entry rather than at the place of use. This speeds troubleshooting up a little bit.
2) Use `ADMIN_DATABASE_REPLICA_SET_NAME=os.getenv('ADMIN_DATABASE_REPLICA_SET_NAME')' followed with 'if ADMIN_DATABASE_REPLICA_SET_NAME is None` similar to `ADMIN_DATABASE`. This will help troubleshooting and it will identify critical input.

**Comment by wduckitt** [comment]
thanks, seems like only an minor issue. please submit a pull request

**Comment by wduckitt** [comment]
added check and will merge in V3.0.1
