### ISSUE TITLE
pyMongoUtils.py references urllib without impor

### ISSUE THREAD

**Issue by hanak** [wduckitt/React-Automation-Studio#27]
**Problem**
Function `OpenMongoDbClient` references `urllib` without `import urllib`. While this might work, it depends on circumstances.

**Example**
While using `utils/python/mongoDb/pyMongoUtils.py` I run into a failure to list database due to authentication even though I supplied the environment variables `MONGO_ROOT_USERNAME` and `MONGO_ROOT_PASSWORD`. After printing the exception, I noticed the `mongoAuth` is `False` and it is caused by a missing symbol `urllib`. Even though this is a side-effect of my experiments with other modules, I would expect the code to be that fragile.

**Proposed solution**
* Add `import urllib`.
* While reporting a failure in connecting to the DB, include a hint whether authentication was used or whether authentication was not used. It seems to me this might help differentiate between missing credentials and invalid credentials.

**Comment by wduckitt** [comment]
thanks, seems like only an minor issue.please submit a pull request

**Comment by wduckitt** [comment]
made change in a new branch ,will merge in V3.0.1
