### ISSUE TITLE
setupNginx.dev.sh reports a warning in the if condition

### ISSUE THREAD

**Issue by hanak** [wduckitt/React-Automation-Studio#28]
**Problem**
Running the script `nginx/setupNginx.dev.sh` yields the message `setupNginx.dev.sh: line 6: [: ==: unary operator expected` which is triggered by the line `if [ $SECURE == "true" ]`.

**Proposed solution**
https://stackoverflow.com/questions/13617843/unary-operator-expected-error-in-bash-if-condition

**Comment by wduckitt** [comment]
thanks, seems like only an minor issue.please submit a pull request

**Comment by wduckitt** [comment]
will merge in V3.0.1
