### ISSUE TITLE
requirements.txt is not compatible with google-api-python-client 2.10.0

### ISSUE THREAD

**Issue by hanak** [wduckitt/React-Automation-Studio#30]
**Problem**
While running `pip -r requirements.txt` I noticed warnings/errors:
```
google-api-core 1.30.0 requires six>=1.13.0, but you'll have six 1.11.0 which is incompatible.
google-api-python-client 2.10.0 requires six<2dev,>=1.13.0, but you'll have six 1.11.0 which is incompatible.
```

**Observation**
It seems that `pvServer/requirements.txt` declares it requires a specific version of the package `six` through `six==1.11.0` while it does not specify the version in case of the package `google-api-python-client`. As a consequence, `google-api-python-client` will result into the latest version.

**Comment by wduckitt** [comment]
Hi 
I realise you are not building in the container, but his warning does not appear when building the container. Perhaps your version of python is newer than 3.8.7 as used in the container. I have versioned the google api though and will merge in V3.0.1

**Comment by hanak** [comment]
Hello,

Thank you for your response and for addressing the reported problem. You are correct, I run pvServer outside the container on Windows in this case which is not supported (as far as I recall). I run python 3.8.8 and pip 20.2.3. Maybe, it is the combination of both which makes the difference. I am not familiar with this detail in pip to tell more. Nevertheless, setting the version explicitly will solve the problem. I am sorry for inconvenience.
