### ISSUE TITLE
ProgressBar with fixed height?

### ISSUE THREAD

**Issue by darcato** [wduckitt/React-Automation-Studio#4]
Hello,
I am trying to use the `ProgressBar` widget but I can't resize it to the desired height. Looking inside your code I found these lines of code:

```
function ProgressBarComponent(props) {
      [...]
      const width=props.width;
      const height=props.width/2;
```

Is this a design choice? Why having the height set to half the width?
By replacing the height setting with:
```
      const height=props.height;
```
I was able to adapt it to the external container. Is this reasonable?

Thanks,
Davide

PS: Great project by the way!

**Comment by wduckitt** [comment]
Hi Davide

Thanks for pointing it out. I will fix it and also I'll add in an aspect ratio that scales the height to the width, this will keep the progress bar responsive if the height is not defined and the width is set to 100% of the parent container.

Regards,

William

**Comment by wduckitt** [comment]
Hi   Davide

The changes are in the master.
I'll make new release soon.

Regards,

William

**Comment by darcato** [comment]
Thanks for the fix, I tried to use the new code some days ago and everything works now!

Davide
